### ISSUE TITLE
Flash MS-108wr

### ISSUE THREAD

**Issue by gysmo38** [plutec/shutterFW#11]
Hello,

I have a MS-108WR. Do you knwon how I can flash it?

I do not find a tutoriel with pinout.

Thank you

**Comment by plutec** [comment]
Hi, I desoldered the ESP in the board and solder following the indications marked in the ESP (GND, 3V3, TX, RX and GPIO0).
That version I think is with RF also, and I don't know how is the board. Please, share some pictures.

Thanks.

**Comment by gysmo38** [comment]
Thank you for your answer. I made research, I have a version with the new board that is not an ESP :'( So I could not flash it...

**Comment by plutec** [comment]
Which MCU has?

**Comment by gysmo38** [comment]
I found the information [here](https://templates.blakadder.com/unsupported/moes-MS-104.html)
It is the board BEKEN BK7231QN40
I compare with picture from this forum: [here](https://community.home-assistant.io/t/unkown-tuya-chip/153591)
Some users manage to replace it with an ESP but it llok too complicated for me. 
I search a module for curtain motor with direct RF for controlling it. I will use it for my parents and I would thay can use the mudule even if Homeassitant fail.

**Comment by plutec** [comment]
I have the MS108 (with ESP) also controlled with a tipical interrupter with 2 positions. In case HA failed, I can control manually.
